<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-J6JNDT39" failures="1" tests="4" name="Smoke" time="9.313" errors="0" timestamp="2022-05-10T00:23:32 EDT">
  <testcase classname="testCases.HomePageTest" name="t04_select_array" time="2.577"/>
  <testcase classname="testCases.ArrayTest" name="t01_click_array_in_python" time="2.809">
    <failure type="java.lang.AssertionError" message="expected [Login] but found [Arrays in Python]">
      <![CDATA[java.lang.AssertionError: expected [Login] but found [Arrays in Python]
at testCases.ArrayTest.t01_click_array_in_python(ArrayTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- t01_click_array_in_python -->
  <testcase classname="testCases.ArraysinPythonTest" name="t01_create_arrays" time="2.55"/>
  <testcase classname="testCases.AssessmentArrayTest" name="t01_click_runtest" time="0.661"/>
  <testcase classname="testCases.HomePageTest" name="t03_press_linked_list" time="0.0">
    <ignored/>
  </testcase> <!-- t03_press_linked_list -->
  <testcase classname="testCases.HomePageTest" name="t01_sign_in" time="0.0">
    <ignored/>
  </testcase> <!-- t01_sign_in -->
</testsuite> <!-- Smoke -->
